FROM node:17-alpine3.14

WORKDIR /frontend
RUN npm uninstall -g create-react-app
RUN npm install -g create-react-app
RUN npm install axios react-router react-bootstrap \
bootstrap react-router-dom node-sass redux@4.0.4
